language: node_js

node_js:
  - "node"

script: true

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  secure: "BLKGfAdRg0h8/1EA9AhoTOWa19tKYrqpaaiZLJF2xSRCa16Tz6vu0mKRoCbB0YWD09ZSM2T0+wvRwyXa1KTl94XVeQuI6SrlXUu8tLU168RiiraD0LS2JdcRGI/klSDD8aOIm+IXS0cFgNXh3XtZ35GIvEer7ZLFjI/3OOFLtfkqlEFM/FoVu4y9GOWJin3hpABsDiYDpXPIQNqBqGWaZjlmOBoBFSiJt51hXtKHY2CJ2VC5RWT/9HPk4GbXsQJX6zcP/K+9VFwmrJuEgt3KxfRgvEoDYbEP9LipBku0Srt06UPkCh57CfTccp5y9nKkNvMg/YhaWtQcb5XvT4vLARbZntxnE1a+4i3kwMLg5Zhaea0IHx3CMpOw+HdL5N5ijlaekwZznqubsuhI+mW0hKIWYhLFjImrh7u6fOBvfxnutv3pUCD1/WkRnLfsRhLw4NTEPnIrsOMWnFgGX5X3tbXDzCAl41/XZsSUySig23EpUCazWxdlshYHcfDEY44basdMcZ9mBg9kawFcY7d6ZHeyEOx201m1SbgGZM6Q6PIhjF3/aXoLrLemkL8knS3HR+oi1QWXG+RMpMP9iER0xKXW0K+Kmc0JnF2sReZL83vXDFn0vjP/FzPeKCjwoZwQt9QO/e9nR7O2MjdQ/oLaMTTH42CMVIlf9jZRtSSakIM="

